version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports: 
      - 80:80
    volumes:
      - /root/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/wwwroot/:/usr/share/nginx/wwwroot/
