version: '3.7'
services:
  gitlab-runner:
    image: zsp/runner:v1
    container_name: gitlab-runner
    restart: always
    privileged: true
    volumes:
      - /usr/local/docker/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
