version: '3.7'
services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    restart: always
    ports: 
      - 9200:9200
    networks:
      - elastic
    environment:
      - "discovery.type=single-node"

  kibana:
    image: kibana
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    name: elastic