version: '3.1'
services:
   gitlab:
      image: 'gitlab/gitlab-ce'
      container_name: 'gitlab_ce'
      privileged: true
      hostname: 'www.airbash.cn'
      ports:
        - '8080:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - /usr/local/docker/gitlab/config:/etc/gitlab
        - /usr/local/docker/gitlab/data:/var/opt/gitlab
        - /usr/local/docker/gitlab/logs:/var/log/gitlab
