version: '3.6'
services:
   gitlab:
      image: 'gitlab/gitlab-ce'
      container_name: 'gitlab'
      privileged: true
      hostname: 'www.airbash.cn'
      ports:
        - '8080:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - $HOME/docker/gitlab/config:/etc/gitlab
        - $HOME/docker/gitlab/data:/var/opt/gitlab
        - $HOME/docker/gitlab/logs:/var/log/gitlab
      deploy:
        resources:
          limits:
            memory: 2.5G
              