version: '3.7'
services:
   fastdfs1:
      build: ./
      restart: always
      image: airbash/fastdfs:v1
      container_name: fastdfs
      volumes:
         - /root/fastdfs/data/storage:/fastdfs/storage
      network_mode: host